Candidate: CVE-2023-26151
PublicDate: 2023-10-03 05:15:00 UTC
References:
 https://gist.github.com/artfire52/1540b234350795e0ecb4d672608dbec8
 https://github.com/FreeOpcUa/opcua-asyncio/releases/tag/v0.9.96
 https://security.snyk.io/vuln/SNYK-PYTHON-ASYNCUA-5673709
 https://github.com/FreeOpcUa/opcua-asyncio/issues/1013
 https://github.com/FreeOpcUa/opcua-asyncio/pull/1039
 https://github.com/FreeOpcUa/opcua-asyncio/commit/f6603daa34a93a658f0e176cb0b9ee5a6643b262
 https://www.cve.org/CVERecord?id=CVE-2023-26151
Description:
 Versions of the package asyncua before 0.9.96 are vulnerable to Denial of
 Service (DoS) such that an attacker can send a malformed packet and as a
 result, the server will enter into an infinite loop and consume excessive
 memory.
Ubuntu-Description:
Notes:
Mitigation:
Bugs:
Priority: medium
Discovered-by:
Assigned-to:
CVSS:
 nvd: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H [7.5 HIGH]

Patches_python-opcua:
upstream_python-opcua: needs-triage
trusty_python-opcua: ignored (end of standard support)
xenial_python-opcua: ignored (end of standard support)
bionic_python-opcua: ignored (end of standard support)
esm-apps/bionic_python-opcua: needs-triage
focal_python-opcua: needs-triage
esm-apps/focal_python-opcua: needs-triage
jammy_python-opcua: needs-triage
esm-apps/jammy_python-opcua: needs-triage
lunar_python-opcua: DNE
mantic_python-opcua: DNE
noble_python-opcua: DNE
oracular_python-opcua: DNE
plucky_python-opcua: DNE
devel_python-opcua: DNE
