Candidate: CVE-2023-49297
PublicDate: 2023-12-05 21:15:00 UTC
References:
 https://github.com/iterative/PyDrive2/security/advisories/GHSA-v5f6-hjmf-9mc5
 https://github.com/iterative/PyDrive2/commit/c57355dc2033ad90b7050d681b2c3ba548ff0004 (1.16.2)
 https://github.com/iterative/PyDrive2/commit/c57355dc2033ad90b7050d681b2c3ba548ff0004
 https://www.cve.org/CVERecord?id=CVE-2023-49297
Description:
 PyDrive2 is a wrapper library of google-api-python-client that simplifies
 many common Google Drive API V2 tasks. Unsafe YAML deserilization will
 result in arbitrary code execution. A maliciously crafted YAML file can
 cause arbitrary code execution if PyDrive2 is run in the same directory as
 it, or if it is loaded in via `LoadSettingsFile`. This is a deserilization
 attack that will affect any user who initializes GoogleAuth from this
 package while a malicious yaml file is present in the same directory. This
 vulnerability does not require the file to be directly loaded through the
 code, only present. This issue has been addressed in commit `c57355dc`
 which is included in release version `1.16.2`. Users are advised to
 upgrade. There are no known workarounds for this vulnerability.
Ubuntu-Description:
Notes:
Mitigation:
Bugs:
Priority: medium
Discovered-by:
Assigned-to:
CVSS:
 github: CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:L/I:N/A:N [3.3 LOW]
 nvd: CVSS:3.1/AV:L/AC:L/PR:N/UI:R/S:U/C:H/I:H/A:H [7.8 HIGH]

Patches_pydrive2:
upstream_pydrive2: needs-triage
trusty_pydrive2: ignored (end of standard support)
xenial_pydrive2: ignored (end of standard support)
bionic_pydrive2: ignored (end of standard support)
focal_pydrive2: DNE
jammy_pydrive2: DNE
lunar_pydrive2: ignored (end of life, was needs-triage)
mantic_pydrive2: ignored (end of life, was needs-triage)
noble_pydrive2: needs-triage
esm-apps/noble_pydrive2: needs-triage
oracular_pydrive2: needs-triage
plucky_pydrive2: needs-triage
devel_pydrive2: needs-triage
