PublicDateAtUSN: 2020-12-09 07:15:00 UTC
Candidate: CVE-2020-29651
PublicDate: 2020-12-09 07:15:00 UTC
References:
 https://github.com/pytest-dev/py/issues/256
 https://github.com/pytest-dev/py/pull/257
 https://ubuntu.com/security/notices/USN-5138-1
 https://www.cve.org/CVERecord?id=CVE-2020-29651
Description:
 A denial of service via regular expression in the py.path.svnwc component
 of py (aka python-py) through 1.9.0 could be used by attackers to cause a
 compute-time denial of service attack by supplying malicious input to the
 blame functionality.
Ubuntu-Description:
Notes:
Mitigation:
Bugs:
Priority: medium
Discovered-by:
Assigned-to: 
CVSS:
 nvd: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H [7.5 HIGH]


Patches_python-py:
 upstream: https://github.com/pytest-dev/py/pull/257/commits/4a9017dc6199d2a564b6e4b0aa39d6d8870e4144
upstream_python-py: released (1.10.0-1)
precise/esm_python-py: DNE
trusty_python-py: ignored (end of standard support)
trusty/esm_python-py: DNE
esm-infra-legacy/trusty_python-py: DNE
xenial_python-py: ignored (end of standard support, was needs-triage)
esm-apps/xenial_python-py: needed
bionic_python-py: released (1.5.2-1ubuntu0.1)
esm-apps/bionic_python-py: released (1.5.2-1ubuntu0.1)
focal_python-py: released (1.8.1-1ubuntu0.1)
esm-apps/focal_python-py: released (1.8.1-1ubuntu0.1)
groovy_python-py: ignored (end of life)
hirsute_python-py: not-affected (1.10.0-1)
impish_python-py: not-affected (1.10.0-1)
jammy_python-py: not-affected (1.10.0-1)
esm-apps/jammy_python-py: not-affected (1.10.0-1)
kinetic_python-py: not-affected (1.10.0-1)
lunar_python-py: not-affected (1.10.0-1)
mantic_python-py: not-affected (1.10.0-1)
noble_python-py: not-affected (1.10.0-1)
esm-apps/noble_python-py: not-affected (1.10.0-1)
oracular_python-py: not-affected (1.10.0-1)
plucky_python-py: not-affected (1.10.0-1)
devel_python-py: not-affected (1.10.0-1)
