Candidate: CVE-2024-6221
PublicDate: 2024-08-18 19:15:00 UTC
References:
 https://www.cve.org/CVERecord?id=CVE-2024-6221
 https://huntr.com/bounties/a42935fc-6f57-4818-bca4-3d528235df4d
Description:
 A vulnerability in corydolphin/flask-cors version 4.0.1 allows the
 `Access-Control-Allow-Private-Network` CORS header to be set to true by
 default. This behavior can expose private network resources to unauthorized
 external access, leading to significant security risks such as data
 breaches, unauthorized access to sensitive information, and potential
 network intrusions.
Ubuntu-Description:
Notes:
Mitigation:
Bugs:
Priority: medium
Discovered-by:
Assigned-to:
CVSS:
 huntr.dev: CVSS:3.0/AV:N/AC:L/PR:N/UI:R/S:U/C:H/I:N/A:N [6.5 MEDIUM]
 nvd: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:H/I:N/A:N [7.5 HIGH]


Patches_python-flask-cors:
 upstream: https://github.com/corydolphin/flask-cors/commit/7ae310c56ac30e0b94fb42129aa377bf633256ec
 upstream: https://github.com/corydolphin/flask-cors/commit/c8514760cf03fcce16d77f6db7007aad429c4548
upstream_python-flask-cors: released (5.0.0)
focal_python-flask-cors: ignored (end of standard support, was needs-triage)
esm-apps/focal_python-flask-cors: needed
jammy_python-flask-cors: needed
esm-apps/jammy_python-flask-cors: needed
noble_python-flask-cors: needed
esm-apps/noble_python-flask-cors: needed
oracular_python-flask-cors: needed
plucky_python-flask-cors: not-affected (5.0.0-1)
devel_python-flask-cors: not-affected (6.0.1-1)
