Candidate: CVE-2025-32414
PublicDate: 2025-04-08 03:15:00 UTC
References:
 https://www.cve.org/CVERecord?id=CVE-2025-32414
Description:
 In libxml2 before 2.13.8 and 2.14.x before 2.14.2, out-of-bounds memory
 access can occur in the Python API (Python bindings) because of an
 incorrect return value. This occurs in xmlPythonFileRead and
 xmlPythonFileReadRaw because of a difference between bytes and characters.
Ubuntu-Description:
Notes:
Mitigation:
Bugs:
 https://gitlab.gnome.org/GNOME/libxml2/-/issues/889
Priority: medium
Discovered-by:
Assigned-to: mdeslaur(main), leosilva(esm)
CVSS:

Patches_libxml2:
 upstream: https://gitlab.gnome.org/GNOME/libxml2/-/commit/8d415b8911be26b12b85497f7cc57143b5321787
 upstream: https://gitlab.gnome.org/GNOME/libxml2/-/commit/4d24aa22ac5811235904a02530fd8dce01c65f68 (test)
upstream_libxml2: needs-triage
esm-infra-legacy/trusty_libxml2: needs-triage
esm-infra/xenial_libxml2: needs-triage
esm-infra/bionic_libxml2: needs-triage
focal_libxml2: needs-triage
jammy_libxml2: needs-triage
noble_libxml2: needs-triage
oracular_libxml2: needs-triage
plucky_libxml2: needs-triage
devel_libxml2: needs-triage
