Candidate: CVE-2025-55558
PublicDate: 2025-09-26
References:
 https://www.cve.org/CVERecord?id=CVE-2025-55558
 https://gist.github.com/shaoyuyoung/0e7d2a586297ae9c8ed14d8706749efc
 https://github.com/pytorch/pytorch/issues/151523
 https://github.com/pytorch/pytorch/pull/151887
Description:
 A buffer overflow occurs in pytorch v2.7.0 when a PyTorch model consists of
 torch.nn.Conv2d, torch.nn.functional.hardshrink, and
 torch.Tensor.view-torch.mv() and is compiled by Inductor, leading to a
 Denial of Service (DoS).
Ubuntu-Description:
Notes:
Mitigation:
Bugs:
Priority: medium
Discovered-by:
Assigned-to:
CVSS:
 cisa-adp: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H [7.5 HIGH]

Patches_pytorch:
upstream_pytorch: needs-triage
jammy_pytorch: needs-triage
esm-apps/jammy_pytorch: needs-triage
noble_pytorch: DNE
plucky_pytorch: needs-triage
devel_pytorch: needs-triage
