PublicDateAtUSN: 2019-07-01 14:00:00 UTC
Candidate: CVE-2019-12781
CRD: 2019-07-01 14:00:00 UTC
PublicDate: 2019-07-01 14:15:00 UTC
References:
 https://ubuntu.com/security/notices/USN-4043-1
 https://www.cve.org/CVERecord?id=CVE-2019-12781
Description:
 An issue was discovered in Django 1.11 before 1.11.22, 2.1 before 2.1.10,
 and 2.2 before 2.2.3. An HTTP request is not redirected to HTTPS when the
 SECURE_PROXY_SSL_HEADER and SECURE_SSL_REDIRECT settings are used, and the
 proxy connects to Django via HTTPS. In other words,
 django.http.HttpRequest.scheme has incorrect behavior when a client uses
 HTTP.
Ubuntu-Description:
Notes:
Bugs:
Priority: medium
Discovered-by: Gavin Wahl
Assigned-to:
CVSS:
 nvd: CVSS:3.0/AV:N/AC:L/PR:N/UI:N/S:U/C:L/I:N/A:N [5.3 MEDIUM]


Patches_python-django:
upstream_python-django: needs-triage
precise/esm_python-django: DNE
trusty_python-django: ignored (end of standard support)
trusty/esm_python-django: ignored (end of ESM support, was needed)
esm-infra-legacy/trusty_python-django: needed
xenial_python-django: released (1.8.7-1ubuntu5.9)
esm-infra/xenial_python-django: released (1.8.7-1ubuntu5.9)
bionic_python-django: released (1:1.11.11-1ubuntu1.4)
esm-infra/bionic_python-django: released (1:1.11.11-1ubuntu1.4)
cosmic_python-django: released (1:1.11.15-1ubuntu1.3)
disco_python-django: released (1:1.11.20-1ubuntu0.1)
focal_python-django: not-affected (1:1.11.22-1)
esm-infra/focal_python-django: not-affected (1:1.11.22-1)
jammy_python-django: not-affected (1:1.11.22-1)
kinetic_python-django: not-affected (1:1.11.22-1)
lunar_python-django: not-affected (1:1.11.22-1)
mantic_python-django: not-affected (1:1.11.22-1)
noble_python-django: not-affected (1:1.11.22-1)
oracular_python-django: not-affected (1:1.11.22-1)
plucky_python-django: not-affected (1:1.11.22-1)
questing_python-django: not-affected (1:1.11.22-1)
devel_python-django: not-affected (1:1.11.22-1)
