Candidate: CVE-2025-2998
PublicDate: 2025-03-31 14:15:00 UTC
References:
 https://www.cve.org/CVERecord?id=CVE-2025-2998
 https://github.com/pytorch/pytorch/issues/149622
 https://github.com/pytorch/pytorch/issues/149622#issue-2935495265
 https://vuldb.com/?ctiid.302047
 https://vuldb.com/?id.302047
 https://vuldb.com/?submit.524151
Description:
 A vulnerability was found in PyTorch 2.6.0. It has been declared as
 critical. Affected by this vulnerability is the function
 torch.nn.utils.rnn.pad_packed_sequence. The manipulation leads to memory
 corruption. Local access is required to approach this attack. The exploit
 has been disclosed to the public and may be used.
Ubuntu-Description:
Notes:
Mitigation:
Bugs:
Priority: medium
Discovered-by:
Assigned-to:
CVSS:
 vuldb: CVSS:3.1/AV:L/AC:L/PR:L/UI:N/S:U/C:L/I:L/A:L [5.3 MEDIUM]
 vuldb: CVSS:4.0/AV:L/AC:L/AT:N/PR:L/UI:N/VC:L/VI:L/VA:L/SC:N/SI:N/SA:N/E:X/CR:X/IR:X/AR:X/MAV:X/MAC:X/MAT:X/MPR:X/MUI:X/MVC:X/MVI:X/MVA:X/MSC:X/MSI:X/MSA:X/S:X/AU:X/R:X/V:X/RE:X/U:X [4.8 MEDIUM]

Patches_pytorch:
upstream_pytorch: needs-triage
focal_pytorch: DNE
esm-infra/focal_pytorch: DNE
jammy_pytorch: needs-triage
esm-apps/jammy_pytorch: needs-triage
noble_pytorch: DNE
oracular_pytorch: needs-triage
plucky_pytorch: needs-triage
devel_pytorch: needs-triage
