PublicDateAtUSN: 2025-01-14 14:00:00 UTC
Candidate: CVE-2024-56374
PublicDate: 2025-01-14 19:15:00 UTC
CRD: 2025-01-14 14:00:00 UTC
References:
 https://www.cve.org/CVERecord?id=CVE-2024-56374
 https://ubuntu.com/security/notices/USN-7205-1
 https://ubuntu.com/security/notices/USN-7205-2
Description:
 An issue was discovered in Django 5.1 before 5.1.5, 5.0 before 5.0.11, and
 4.2 before 4.2.18. Lack of upper-bound limit enforcement in strings passed
 when performing IPv6 validation could lead to a potential denial-of-service
 attack. The undocumented and private functions clean_ipv6_address and
 is_valid_ipv6_address are vulnerable, as is the
 django.forms.GenericIPAddressField form field. (The
 django.db.models.GenericIPAddressField model field is not affected.)
Ubuntu-Description:
Notes:
Mitigation:
Bugs:
Priority: medium
Discovered-by:
Assigned-to: leosilva
CVSS:
 mitre: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:C/C:N/I:N/A:L [5.8 MEDIUM]
 nvd: CVSS:3.1/AV:N/AC:L/PR:N/UI:N/S:U/C:N/I:N/A:H [7.5 HIGH]

Patches_python-django:
upstream_python-django: needs-triage
esm-infra-legacy/trusty_python-django: needs-triage
esm-infra/xenial_python-django: needs-triage
esm-infra/bionic_python-django: released (1:1.11.11-1ubuntu1.21+esm9)
focal_python-django: released (2:2.2.12-1ubuntu0.27)
esm-infra/focal_python-django: released (2:2.2.12-1ubuntu0.27)
jammy_python-django: released (2:3.2.12-2ubuntu1.16)
noble_python-django: released (3:4.2.11-1ubuntu1.5)
oracular_python-django: released (3:4.2.15-1ubuntu1.2)
plucky_python-django: released (3:4.2.18-1)
devel_python-django: released (3:4.2.18-1)
