PublicDateAtUSN: 2024-12-04 15:00:00 UTC
Candidate: CVE-2024-53908
PublicDate: 2024-12-06 12:15:00 UTC
CRD: 2024-12-04 15:00:00 UTC
References:
 https://www.cve.org/CVERecord?id=CVE-2024-53908
 https://ubuntu.com/security/notices/USN-7136-1
Description:
 An issue was discovered in Django 5.1 before 5.1.4, 5.0 before 5.0.10, and
 4.2 before 4.2.17. Direct usage of the django.db.models.fields.json.HasKey
 lookup, when an Oracle database is used, is subject to SQL injection if
 untrusted data is used as an lhs value. (Applications that use the
 jsonfield.has_key lookup via __ are unaffected.)
Ubuntu-Description:
Notes:
 mdeslaur> There is no JSONField model field in focal and earlier.
 mdeslaur> Lookup expressions were introduced here:
 mdeslaur> https://github.com/django/django/commit/f42ccdd835e5b3f0914b5e6f87621c648136ea36
 mdeslaur> so jammy doesn't appear to be affected.
Mitigation:
Bugs:
Priority: medium
Discovered-by: Seokchan Yoon
Assigned-to:
CVSS:

Patches_python-django:
upstream_python-django: released (4.2.17)
esm-infra-legacy/trusty_python-django: not-affected (code not present)
trusty/esm_python-django: not-affected (code not present)
esm-infra/xenial_python-django: not-affected (code not present)
esm-infra/bionic_python-django: not-affected (code not present)
focal_python-django: not-affected (code not present)
jammy_python-django: not-affected (code not present)
noble_python-django: released (3:4.2.11-1ubuntu1.4)
oracular_python-django: released (3:4.2.15-1ubuntu1.1)
devel_python-django: released (3:4.2.17-2)
