PublicDateAtUSN: 2020-06-03 10:00:00 UTC
Candidate: CVE-2020-13254
CRD: 2020-06-03 10:00:00 UTC
PublicDate: 2020-06-03 14:15:00 UTC
References: 
 https://ubuntu.com/security/notices/USN-4381-1
 https://ubuntu.com/security/notices/USN-4381-2
 https://www.cve.org/CVERecord?id=CVE-2020-13254
Description:
 An issue was discovered in Django 2.2 before 2.2.13 and 3.0 before 3.0.7.
 In cases where a memcached backend does not perform key validation, passing
 malformed cache keys could result in a key collision, and potential data
 leakage.
Ubuntu-Description: 
Notes: 
Mitigation: 
Bugs: 
Priority: medium
Discovered-by:
Assigned-to:
CVSS:
 nvd: CVSS:3.1/AV:N/AC:H/PR:N/UI:N/S:U/C:H/I:N/A:N [5.9 MEDIUM]


Patches_python-django:
upstream_python-django: released (2.2.13,3.0.7)
precise/esm_python-django: DNE
trusty_python-django: ignored (end of standard support)
trusty/esm_python-django: released (1.6.11-0ubuntu1.3+esm1)
esm-infra-legacy/trusty_python-django: released (1.6.11-0ubuntu1.3+esm1)
xenial_python-django: released (1.8.7-1ubuntu5.13)
esm-infra/xenial_python-django: released (1.8.7-1ubuntu5.13)
bionic_python-django: released (1:1.11.11-1ubuntu1.9)
esm-infra/bionic_python-django: released (1:1.11.11-1ubuntu1.9)
eoan_python-django: released (1:1.11.22-1ubuntu1.4)
focal_python-django: released (2:2.2.12-1ubuntu0.1)
esm-infra/focal_python-django: released (2:2.2.12-1ubuntu0.1)
devel_python-django: released (2:2.2.12-1ubuntu1)
